Repository softeer5th/DE-team1-suriname, pull requests merged in 2025-02, with the labels that each got.

#3 Feat: KBS 크롤링 기능 구현
  extract/kbs_crawler.py
Labels: ✨ Feature

#4 Feat: SBS 크롤러 구현
  extract/sbs_crawler.py
  type/__init__.py
  type/news_crawler.py
Labels: ✨ Feature

#6 Feat: 커뮤니티 모니터 람다 함수 구현
  transform/lambda_task_monitor.py
Labels: ✨ Feature

#8 Fix: 크롤러 키워드 포함하도록 수정
  extract/news/kbs_crawler.py
  extract/news/sbs_crawler.py
  extract/news/type/news_crawler.py
Labels: 🔨 Refactor

#9 Feat: SBS 크롤러가 시간비교후 저장 하도록 구현
  extract/news/sbs_crawler.py
Labels: ✨ Feature

#11 Feat: 뉴스데이터 사고 count 및 s3 저장 구현
  extract/news/kbs_crawler.py
  extract/news/sbs_crawler.py
  transform/emr_transform_news.py
Labels: ✨ Feature

#14 Feat: 메인테이블 업데이트 및 임계치 확인 로직 구현
  transform/emr_transform_news.py
Labels: ✨ Feature

#15 Feat: accumlated_table 생성
  sql/initiate_accumulate_table.sql
Labels: ✨ Feature

#18 Feat: 연합뉴스 크롤러 구현
  extract/news/yna_crawler.py
Labels: ✨ Feature

#17 Feat: 커뮤니티 키워드 검색
  extract/community/lambda_function.py
  transform/emr_transform_community.py
  transform/emr_transform_news.py
Labels: ✨ Feature

#19 Refactor: 뉴스 크롤러가 BaseCrawler를 상속받아 구현하도록 수정
  extract/news/base_crawler.py
  extract/news/kbs_crawler.py
  extract/news/lambda_function.py
  extract/news/sbs_crawler.py
  extract/news/yna_crawler.py
Labels: ✨ Feature, 🔨 Refactor

#21 Feat: YTN 뉴스 크롤러 구현
  extract/news/ytn_crawler.py
Labels: ✨ Feature

#22 Feat: EMR 트리거 람다 구현
  extract/news/base_crawler.py
  transform/lambda_emr_news_trigger.py
Labels: ✨ Feature

#26 Feat: EMR에서 이슈점수를 GPT를 활용해 계산하는 기능 구현
  extract/news/crawler/sbs_crawler.py
  extract/news/crawler/yna_crawler.py
  transform/emr_transform_community.py
  transform/emr_transform_news.py
Labels: 🐞 Bug, ✨ Feature

#28 Feat: 이슈 주의도 계산 및 최종 테이블 업데이트 함수 구현
  load/load_final_table/lambda_function.py
  load/load_news/lambda_function.py
Labels: ✨ Feature

#30 Feat: Slack Alert 기능 구현
  sns/slack_alert.py
Labels: ✨ Feature

#31 Feat: 에어플로우 세팅
  airflow/dags/community_dag.py
  airflow/dags/news_dag.py
  airflow/plugins/__init__.py
  airflow/plugins/slack_alert_develop.py
  extract/community/dcinside_crawler.py
  extract/community/lambda_function.py
  extract/community/type/community_crawler.py
  extract/news/crawler/lambda_function.py
  sql/initiate_accumulate_table.sql
  test_bobae/Dockerfile
  transform/emr_transform_community.py
  transform/emr_transform_news.py
Labels: ✨ Feature

#32 Feat: Femco 크롤러 구현
  extract/community/Dockerfile
  extract/community/femco_crawler.py
  extract/community/lambda_function.py
Labels: ✨ Feature

#33 Feat: 조회수 기준 5개 커뮤니티 게시글 수집 기능 구현
  transform/emr_transform_community.py
  transform/runner_emr_community.py
Labels: ✨ Feature

#34 Feat: 커뮤니티 긍부정 판단 구현
  load/load_final_table/lambda_function.py
  transform/emr_transform_community.py
  transform/runner_emr_community.py
Labels: ✨ Feature
